version: "3"
name: afov-website
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
    networks:
      - afov-cms_network

networks:
  afov-cms_network:
    external: true
