export const NEXT_PUBLIC = {
  HOSTNAME: process.env.NEXT_PUBLIC_HOSTNAME,
  GOOGLE_ANALYTICS_ID: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID,
};

export const CONTENTFUL = {
  SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
  ENV: process.env.CONTENTFUL_ENV,
  MANAGEMENT_TOKEN: process.env.CONTENTFUL_MANAGEMENT_TOKEN,
  ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN,
  PREVIEW_ACCESS_TOKEN: process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN,
  PREVIEW_SECRET: process.env.CONTENTFUL_PREVIEW_SECRET,
  PREVIEW_HOST: process.env.CONTENTFUL_PREVIEW_HOST,
};
