version: "3"
name: afov-cms
services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./public/uploads:/opt/app/public/uploads
      - ./.gcp/afov-sa.json:/secrets/afov-sa.json:ro
    ports:
      - 1337:1337
    networks:
      - afov-cms-network
    depends_on:
      - gcp-sql-proxy
  gcp-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    restart: unless-stopped
    env_file: .env
    command:
      - /cloud_sql_proxy
      - -instances=$GCP_SQL_CONNECTION_NAME=tcp:0.0.0.0:5432
    volumes:
      - ./.gcp/afov-sa.json:/secrets/afov-sa.json:ro
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - afov-cms-network
networks:
  afov-cms-network:
    driver: bridge

  # TODO: Create local clone of prod db workflow
  # afov-cms-db:
  #   container_name: afov-cms-db
  #   platform: linux/amd64
  #   restart: unless-stopped
  #   env_file: .env
  #   image: postgres:14.5-alpine
  #   volumes:
  #     - afov-cms-data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - afov-cms
# volumes:
#   afov-cms-data:

